name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.LuEIJg+XAtmxfQEj8mwI3jfqWnsxA8hAwNoAdauC }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AKIASCZ3EQTLTA2IXCUB }}
      AWS_REGION: ${{ secrets.us-east-1 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
